# Generated by Django 3.0.6 on 2020-06-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Teacher First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Teacher Last name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Student First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Student Last name')),
                ('details', models.TextField(verbose_name='Student Details')),
                ('schoolClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schoolClass')),
            ],
        ),
    ]
