# Generated by Django 3.0.7 on 2020-06-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Teacher First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Teacher Last name')),
                ('hourlyRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Student First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Student Last name')),
                ('enrolNum', models.IntegerField()),
                ('details', models.TextField(verbose_name='Student Details')),
                ('attendence', models.BooleanField()),
                ('schoolClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.SchoolClass')),
            ],
        ),
    ]
